// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: url_shortener.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{0}
}

type PingDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{1}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{2}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int64 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int64 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

type GetURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrlId string `protobuf:"bytes,1,opt,name=short_url_id,json=shortUrlId,proto3" json:"short_url_id,omitempty"`
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetURLRequest) GetShortUrlId() string {
	if x != nil {
		return x.ShortUrlId
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectTo string `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetURLResponse) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

type GetURLsByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetURLsByUserIDRequest) Reset() {
	*x = GetURLsByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsByUserIDRequest) ProtoMessage() {}

func (x *GetURLsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetURLsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{6}
}

type ResponsePairURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	FullUrl  string `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *ResponsePairURL) Reset() {
	*x = ResponsePairURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePairURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePairURL) ProtoMessage() {}

func (x *ResponsePairURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePairURL.ProtoReflect.Descriptor instead.
func (*ResponsePairURL) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *ResponsePairURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ResponsePairURL) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

type GetURLsByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponsePairsUrls []*ResponsePairURL `protobuf:"bytes,1,rep,name=response_pairs_urls,json=responsePairsUrls,proto3" json:"response_pairs_urls,omitempty"`
}

func (x *GetURLsByUserIDResponse) Reset() {
	*x = GetURLsByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsByUserIDResponse) ProtoMessage() {}

func (x *GetURLsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetURLsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *GetURLsByUserIDResponse) GetResponsePairsUrls() []*ResponsePairURL {
	if x != nil {
		return x.ResponsePairsUrls
	}
	return nil
}

type PostURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullUrl string `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *PostURLRequest) Reset() {
	*x = PostURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLRequest) ProtoMessage() {}

func (x *PostURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLRequest.ProtoReflect.Descriptor instead.
func (*PostURLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *PostURLRequest) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

type PostURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *PostURLResponse) Reset() {
	*x = PostURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLResponse) ProtoMessage() {}

func (x *PostURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLResponse.ProtoReflect.Descriptor instead.
func (*PostURLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *PostURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type PostURLBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PostURLBatch) Reset() {
	*x = PostURLBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLBatch) ProtoMessage() {}

func (x *PostURLBatch) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLBatch.ProtoReflect.Descriptor instead.
func (*PostURLBatch) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *PostURLBatch) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PostURLBatch) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PostURLBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestUrls []*PostURLBatch `protobuf:"bytes,1,rep,name=request_urls,json=requestUrls,proto3" json:"request_urls,omitempty"`
}

func (x *PostURLBatchRequest) Reset() {
	*x = PostURLBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLBatchRequest) ProtoMessage() {}

func (x *PostURLBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLBatchRequest.ProtoReflect.Descriptor instead.
func (*PostURLBatchRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *PostURLBatchRequest) GetRequestUrls() []*PostURLBatch {
	if x != nil {
		return x.RequestUrls
	}
	return nil
}

type PostURLBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseUrls []*PostURLBatch `protobuf:"bytes,1,rep,name=response_urls,json=responseUrls,proto3" json:"response_urls,omitempty"`
}

func (x *PostURLBatchResponse) Reset() {
	*x = PostURLBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLBatchResponse) ProtoMessage() {}

func (x *PostURLBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLBatchResponse.ProtoReflect.Descriptor instead.
func (*PostURLBatchResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *PostURLBatchResponse) GetResponseUrls() []*PostURLBatch {
	if x != nil {
		return x.ResponseUrls
	}
	return nil
}

type DeleteURLBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DeleteURLBatch) Reset() {
	*x = DeleteURLBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLBatch) ProtoMessage() {}

func (x *DeleteURLBatch) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLBatch.ProtoReflect.Descriptor instead.
func (*DeleteURLBatch) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteURLBatch) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteURLBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestUrls *DeleteURLBatch `protobuf:"bytes,1,opt,name=request_urls,json=requestUrls,proto3" json:"request_urls,omitempty"`
}

func (x *DeleteURLBatchRequest) Reset() {
	*x = DeleteURLBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLBatchRequest) ProtoMessage() {}

func (x *DeleteURLBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLBatchRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteURLBatchRequest) GetRequestUrls() *DeleteURLBatch {
	if x != nil {
		return x.RequestUrls
	}
	return nil
}

type DeleteURLBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteURLBatchResponse) Reset() {
	*x = DeleteURLBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLBatchResponse) ProtoMessage() {}

func (x *DeleteURLBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLBatchResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLBatchResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{16}
}

type GetUptimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUptimeRequest) Reset() {
	*x = GetUptimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUptimeRequest) ProtoMessage() {}

func (x *GetUptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUptimeRequest.ProtoReflect.Descriptor instead.
func (*GetUptimeRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{17}
}

type GetUptimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uptime int64 `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
}

func (x *GetUptimeResponse) Reset() {
	*x = GetUptimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortener_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUptimeResponse) ProtoMessage() {}

func (x *GetUptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUptimeResponse.ProtoReflect.Descriptor instead.
func (*GetUptimeResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{18}
}

func (x *GetUptimeResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_url_shortener_proto protoreflect.FileDescriptor

var file_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x50,
	0x69, 0x6e, 0x67, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x50, 0x69, 0x6e, 0x67, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x31, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x49, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x5f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x54, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x49, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x55,
	0x52, 0x4c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x60, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x55, 0x52, 0x4c, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x2b, 0x0a, 0x0e,
	0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x0f, 0x50, 0x6f, 0x73,
	0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x47, 0x0a, 0x0c, 0x50, 0x6f, 0x73,
	0x74, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x4c, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x73,
	0x22, 0x4f, 0x0a, 0x14, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x72, 0x6c,
	0x73, 0x22, 0x24, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x50, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x32, 0x8a, 0x04, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x12, 0x33, 0x0a, 0x06, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x42, 0x12, 0x13, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x42, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x13, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x52,
	0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x55,
	0x52, 0x4c, 0x12, 0x14, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x19, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x61, 0x6e, 0x69, 0x6c, 0x6f, 0x76, 0x6b, 0x69, 0x72, 0x69, 0x2f, 0x64, 0x6b, 0x5f, 0x67,
	0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_url_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_proto_rawDescData = file_url_shortener_proto_rawDesc
)

func file_url_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_url_shortener_proto_rawDescData)
	})
	return file_url_shortener_proto_rawDescData
}

var file_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_url_shortener_proto_goTypes = []interface{}{
	(*PingDBRequest)(nil),           // 0: demo.PingDBRequest
	(*PingDBResponse)(nil),          // 1: demo.PingDBResponse
	(*GetStatsRequest)(nil),         // 2: demo.GetStatsRequest
	(*GetStatsResponse)(nil),        // 3: demo.GetStatsResponse
	(*GetURLRequest)(nil),           // 4: demo.GetURLRequest
	(*GetURLResponse)(nil),          // 5: demo.GetURLResponse
	(*GetURLsByUserIDRequest)(nil),  // 6: demo.GetURLsByUserIDRequest
	(*ResponsePairURL)(nil),         // 7: demo.ResponsePairURL
	(*GetURLsByUserIDResponse)(nil), // 8: demo.GetURLsByUserIDResponse
	(*PostURLRequest)(nil),          // 9: demo.PostURLRequest
	(*PostURLResponse)(nil),         // 10: demo.PostURLResponse
	(*PostURLBatch)(nil),            // 11: demo.PostURLBatch
	(*PostURLBatchRequest)(nil),     // 12: demo.PostURLBatchRequest
	(*PostURLBatchResponse)(nil),    // 13: demo.PostURLBatchResponse
	(*DeleteURLBatch)(nil),          // 14: demo.DeleteURLBatch
	(*DeleteURLBatchRequest)(nil),   // 15: demo.DeleteURLBatchRequest
	(*DeleteURLBatchResponse)(nil),  // 16: demo.DeleteURLBatchResponse
	(*GetUptimeRequest)(nil),        // 17: demo.GetUptimeRequest
	(*GetUptimeResponse)(nil),       // 18: demo.GetUptimeResponse
}
var file_url_shortener_proto_depIdxs = []int32{
	7,  // 0: demo.GetURLsByUserIDResponse.response_pairs_urls:type_name -> demo.ResponsePairURL
	11, // 1: demo.PostURLBatchRequest.request_urls:type_name -> demo.PostURLBatch
	11, // 2: demo.PostURLBatchResponse.response_urls:type_name -> demo.PostURLBatch
	14, // 3: demo.DeleteURLBatchRequest.request_urls:type_name -> demo.DeleteURLBatch
	0,  // 4: demo.Shortener.PingDB:input_type -> demo.PingDBRequest
	2,  // 5: demo.Shortener.GetStats:input_type -> demo.GetStatsRequest
	4,  // 6: demo.Shortener.GetURL:input_type -> demo.GetURLRequest
	6,  // 7: demo.Shortener.GetURLsByUserID:input_type -> demo.GetURLsByUserIDRequest
	9,  // 8: demo.Shortener.PostURL:input_type -> demo.PostURLRequest
	12, // 9: demo.Shortener.PostURLBatch:input_type -> demo.PostURLBatchRequest
	15, // 10: demo.Shortener.DeleteURLBatch:input_type -> demo.DeleteURLBatchRequest
	17, // 11: demo.Shortener.GetUptime:input_type -> demo.GetUptimeRequest
	1,  // 12: demo.Shortener.PingDB:output_type -> demo.PingDBResponse
	3,  // 13: demo.Shortener.GetStats:output_type -> demo.GetStatsResponse
	5,  // 14: demo.Shortener.GetURL:output_type -> demo.GetURLResponse
	8,  // 15: demo.Shortener.GetURLsByUserID:output_type -> demo.GetURLsByUserIDResponse
	10, // 16: demo.Shortener.PostURL:output_type -> demo.PostURLResponse
	13, // 17: demo.Shortener.PostURLBatch:output_type -> demo.PostURLBatchResponse
	16, // 18: demo.Shortener.DeleteURLBatch:output_type -> demo.DeleteURLBatchResponse
	18, // 19: demo.Shortener.GetUptime:output_type -> demo.GetUptimeResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_url_shortener_proto_init() }
func file_url_shortener_proto_init() {
	if File_url_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_url_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePairURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteURLBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteURLBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteURLBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUptimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortener_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUptimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_proto = out.File
	file_url_shortener_proto_rawDesc = nil
	file_url_shortener_proto_goTypes = nil
	file_url_shortener_proto_depIdxs = nil
}
